# Generated by Django 2.0.4 on 2018-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0002_request_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='organization',
        ),
        migrations.AddField(
            model_name='request',
            name='organization',
            field=models.ManyToManyField(related_name='requests', to='trrequests.Organization'),
        ),
    ]
