# Generated by Django 2.0.4 on 2018-04-03 14:12

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0004_layerrelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trrequests', '0003_auto_20180403_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='UserRequest',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='request',
            new_name='userrequest'
        ),
    ]
