# Generated by Django 2.0.8 on 2018-08-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_readmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readmodel',
            name='identifier',
            field=models.PositiveIntegerField(),
        ),
    ]
