# Generated by Django 2.0.9 on 2018-11-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tropp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewpoint',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='viewpoint',
            name='point',
        ),
        migrations.AddField(
            model_name='viewpoint',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='terra.Feature'),
        ),
    ]
