# Generated by Django 2.0.9 on 2018-11-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tropp', '0002_auto_20181106_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'permissions': (('manage_all_campaigns', 'Can manage all campaigns'),)},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'get_latest_by': 'date', 'permissions': (('change_state_picture', 'Is able to change the picture state'),)},
        ),
    ]
