# Generated by Django 2.0.9 on 2018-11-07 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tropp', '0003_auto_20181106_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'permissions': (('manage_all_campaigns', 'Can manage all campaigns'),)},
        ),
        migrations.AlterField(
            model_name='document',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tropp.Viewpoint'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='viewpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='tropp.Viewpoint'),
        ),
    ]
