# Generated by Django 2.1.12 on 2019-10-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tropp', '0007_auto_20190725_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='remarks',
        ),
    ]
