image: docker:stable

stages:
  - build
  - run-docker
  - tests
  - stop-docker

variables:
  DOCKER_DRIVER: overlay2
  POSTGRES_DB: dev
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: dev

build:
  stage: build
  script:
    - docker build -t $CI_COMMIT_SHA .

run-docker:
  stage: run-docker
  script:
    - docker run -t -d --env-file docker-ci.env --name=$CI_COMMIT_SHA $CI_COMMIT_SHA

tests:
  stage: tests
  services:
    - mdillon/postgis:10-alpine
  script:
     - docker exec -e POSTGRES_HOST=$MDILLON__POSTGIS_PORT_5432_TCP_ADDR $CI_COMMIT_SHA /code/venv/bin/tox -c /code/tox.ini -e tests,coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  dependencies: 
    - build
    - run-docker

linting:
  stage: tests
  services:
    - mdillon/postgis:10-alpine
  script:
     - docker exec -e POSTGRES_HOST=$MDILLON__POSTGIS_PORT_5432_TCP_ADDR $CI_COMMIT_SHA /code/venv/bin/tox -c /code/tox.ini -e linting
  dependencies: 
    - build
    - run-docker

stop-docker:
  stage: stop-docker
  when: always
  script:
    - docker rm -f $CI_COMMIT_SHA
    - docker rmi -f $CI_COMMIT_SHA
