image: ubuntu:artful

stages:
  - tests
  - linting

variables:
  DOCKER_DRIVER: overlay2
  POSTGRES_DB: dev
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: dev
  POSTGRES_HOST: db

before_script:
- apt-get update
- apt-get install -y python3-pip
- apt-get install -y $(grep -vE "^\s*#" apt.txt  | tr "\n" " ") && apt-get clean all && apt-get autoclean
- virtualenv3 .
- ./bin/pip3 install -r requirements.txt


tests:
  stage: tests
  services:
    - mdillon/postgis:10-alpine
  script:
     - ./bin/tox -c tox.ini -e tests,coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

linting:
  stage: linting
  script:
     - ./bin/tox -c tox.ini -e linting
