image: docker:stable

stages:
  - tests
  - linting

variables:
  DOCKER_DRIVER: overlay2
  POSTGRES_DB: dev
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: dev
  POSTGRES_HOST: db

tests:
  stage: tests
  services:
    - mdillon/postgis:10-alpine
  script:
     - /code/venv/bin/tox -c /code/tox.ini -e tests,coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

linting:
  stage: linting
  script:
     - /code/venv/bin/tox -c /code/tox.ini -e linting
