image: ubuntu:bionic

stages:
  - linting
  - tests

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  DOCKER_DRIVER: overlay2
  POSTGRES_USER: user
  POSTGRES_DB: db
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: starefossen__pgrouting

cache:
  paths:
    - /var/cache/apt/
    - .cache/
    - venv/

before_script:
    - apt-get update
    - apt-get install -y python3-pip
    - apt-get install -y $(grep -vE "^\s*#" apt.txt  | tr "\n" " ")
    - python3 -m venv venv/
    - ./venv/bin/pip3 install -r requirements.txt

tests:
  stage: tests
  tags: [shared-ci-docker]
  services:
    - starefossen/pgrouting:10.1-2.4-2.5
  script:
    - ./venv/bin/tox -c tox.ini -e tests,coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

linting:
  stage: linting
  tags: [shared-ci-docker]
  script:
     - ./venv/bin/tox -c tox.ini -e linting
