image: ubuntu:bionic

stages:
  - linting
  - tests
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  DOCKER_DRIVER: overlay2
  POSTGRES_USER: user
  POSTGRES_DB: db
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: makinacorpus__pgrouting

cache:
  paths:
    - /var/cache/apt/
    - .cache/
    - venv/

before_script:
    - apt-get update
    - apt-get install -y python3-pip
    - apt-get install -y $(grep -vE "^\s*#" apt.txt  | tr "\n" " ")
    - python3 -m venv venv/
    - ./venv/bin/pip3 install -r test-requirements.txt

tests:
  stage: tests
  tags: [shared-ci-docker]
  services:
    - makinacorpus/pgrouting:10.1-2.5.4
  script:
    - ./venv/bin/tox -c tox.ini -e tests,coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

linting:
  stage: linting
  tags: [shared-ci-docker]
  script:
     - ./venv/bin/tox -c tox.ini -e linting

publish_pypi:
  image: python:3.6
  stage: publish
  when: manual
  before_script:
    - echo =========== Deploying on pypi ===========
  only:
    - /^v\d+\.\d+\.\d+([abc]\d*)?$/  # PEP-440 compliant version (tags)
  except:
     - branches 
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PYPI_PASSWORD
    TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload -r pypi dist/*

