# Generated by Django 2.0.7 on 2018-07-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180725_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotifications',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='level',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Information'), ('SUCCESS', 'Succès'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur')], max_length=255),
        ),
    ]
