# Generated by Django 2.0.2 on 2018-02-16 13:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0002_featurerelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='featurerelation',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
