# Generated by Django 2.0.3 on 2018-03-28 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrarequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='terrarequests.Organization'),
            preserve_default=False,
        ),
    ]
