# Generated by Django 2.0.7 on 2018-07-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('template', models.FileField(upload_to='template-7-2018/')),
            ],
        ),
        migrations.DeleteModel(
            name='OdtFile',
        ),
    ]
