# Generated by Django 2.0.7 on 2018-08-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttemplate',
            old_name='template',
            new_name='documenttemplate',
        ),
    ]
