# Generated by Django 2.0.9 on 2018-10-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_generator', '0003_auto_20180911_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'permissions': (('can_upload_documents', 'Is allowed to upload documents'), ('can_update_documents', 'Is allowed to update documents'), ('can_delete_documents', 'Is allowed to delete documents'))},
        ),
    ]
