# Generated by Django 2.0.5 on 2018-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='state',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
