# Generated by Django 2.0.5 on 2018-05-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0002_userrequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userrequests', to='terra.Layer'),
        ),
    ]
