# Generated by Django 2.0.5 on 2018-06-04 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0004_auto_20180517_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrequest',
            options={'permissions': (('can_administrate', 'Has administrator permissions on requests'), ('can_read_self', 'Is able to get own requests'), ('can_read_all', 'Is able to get all requests'), ('can_comment', 'Is able to comment an user request'), ('can_internal_comment', 'Is able to add comments not visible by users'), ('can_change_state', 'Is authorized to change the request state'), ('can_approve', 'Is able to set the approved state'))},
        ),
    ]
