# Generated by Django 2.0.5 on 2018-06-15 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trrequests', '0009_auto_20180607_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='reviewers',
            field=models.ManyToManyField(related_name='to_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
