# Generated by Django 2.0.5 on 2018-06-19 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0010_userrequest_reviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='to_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
