# Generated by Django 2.0.5 on 2018-06-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0012_auto_20180622_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='state',
            field=models.IntegerField(default=100),
        ),
    ]
