# Generated by Django 2.0.7 on 2018-07-09 14:56

from django.db import migrations, models

import terracommon.trrequests.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0013_auto_20180625_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, upload_to=terracommon.trrequests.helpers.rename_comment_attachment),
        ),
        migrations.AddField(
            model_name='comment',
            name='filename',
            field=models.CharField(blank=True, editable=False, help_text='Initial name of the attachment', max_length=255),
        ),
    ]
