# Generated by Django 2.0.6 on 2018-07-02 07:48

import django.db.models.deletion
from django.db import migrations, models

import terracommon.trrequests.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0013_auto_20180625_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('initial_filename', models.CharField(editable=False, max_length=255)),
                ('file', models.FileField(upload_to=terracommon.trrequests.helpers.UploadFileHelpers.rename_file)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='trrequests.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
