# Generated by Django 2.0.7 on 2018-07-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terra', '0010_auto_20180629_0756'),
        ('trrequests', '0014_auto_20180709_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='feature',
        ),
        migrations.AddField(
            model_name='comment',
            name='layer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='terra.Layer'),
        ),
    ]
