# Generated by Django 2.0.7 on 2018-07-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0014_auto_20180709_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='expiry',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
