# Generated by Django 2.0.7 on 2018-07-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0015_userrequest_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='expiry',
            field=models.DateField(default=None, null=True),
        ),
    ]
