# Generated by Django 2.0.7 on 2018-07-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trrequests', '0015_auto_20180723_0946'),
        ('trrequests', '0016_auto_20180723_0832'),
    ]

    operations = [
    ]
